name: Backport PR to another branch
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read

jobs:
  pr_commented:
    name: PR comment
    if: |
      (github.event.issue.pull_request && startsWith(github.event.comment.body, '@logstashmachine backport')) &&
      (github.actor == 'jsvd' || github.actor == 'meh')
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'main'
      - run: git config --global user.email "43502315+logstashmachine@users.noreply.github.com"
      - run: git config --global user.name "logstashmachine"
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - env:
          BODY: ${{ github.event.comment.body }}
        run: |
          echo "branch=$(echo "$BODY" | cut -d " " -f 3)" >> $GITHUB_ENV
      - run: |
          mkdir ~/.elastic && echo ${{ github.token }} >> ~/.elastic/github.token
      - run: pip install requests
      - name: run backport
        run: python devtools/backport ${{ env.branch }} ${{ github.event.issue.number }} --remote=origin --yes
